#!/usr/bin/env python
"""Generate the configuration reference from the code that defines it.

`docs/CONFIGURATION.md` is not written by hand. It is rendered from the field metadata
on `Config`, between the GEN markers, and the docs gate fails if the committed file
differs from what this script produces.

That is the whole anti-drift mechanism for config facts (ADR-0004). The ancestor project
documents one setting as three different values in three places; this makes that
impossible rather than merely discouraged.

Usage:
    python scripts/gen_config_docs.py           # write
    python scripts/gen_config_docs.py --check   # exit 1 if stale, print a diff
"""

from __future__ import annotations

import argparse
import difflib
import sys
import tempfile
from pathlib import Path

# Read the real source, never a cached compile. Python validates a .pyc on
# (mtime, size), so an edit that changes a default WITHOUT changing the file's byte
# length -- 6 to 9, true to True, one flag to another -- can be missed if it lands
# within a single filesystem timestamp tick. This script would then happily report the
# doc as current against code that no longer exists, which is the exact failure it is
# supposed to catch. Observed while building this, not hypothetical.
#
# `-B` / sys.dont_write_bytecode is NOT sufficient: it prevents WRITING a cache, not
# READING an existing stale one. Redirecting the cache to an empty temp directory is
# what actually forces a fresh compile.
sys.pycache_prefix = tempfile.mkdtemp(prefix="cdl-gen-pyc-")

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from claude_delegate_local import config  # noqa: E402

TARGET = ROOT / "docs" / "CONFIGURATION.md"
START = "<!-- GEN:CONFIG:START -->"
END = "<!-- GEN:CONFIG:END -->"

# Field-name prefixes grouped into sections, in render order. A field matching no
# group lands in "Other" -- which is a visible prompt to place it, not a silent bucket.
SECTIONS: list[tuple[str, tuple[str, ...]]] = [
    ("Backend selection", ("models_file", "default_model")),
    ("Path policy", ("workspace_roots", "workdir_roots", "ext_allowlist",
                     "secret_globs_file", "respect_gitignore")),
    ("Context prefetch", ("max_file_tokens", "max_total_prefetch_tokens",
                          "max_file_read_bytes")),
    ("Model-facing tool limits", ("max_read_chars", "max_write_bytes",
                                  "run_bash_timeout")),
    ("Generation budgets", ("max_tokens", "thinking_default",
                            "thinking_max_tokens_floor", "resend_reasoning",
                            "tool_call_temperature")),
    ("Agentic loop", ("max_turns_default", "max_turns_hard_cap",
                      "keep_tool_results", "max_batch_size")),
    ("Timeouts and retries", ("turn_timeout", "connect_timeout", "dispatch_timeout",
                              "retry_max_attempts", "retry_base_delay")),
    ("Admission control", ("max_inflight_seqs", "kv_token_budget",
                           "large_prefill_tokens", "max_inflight_large_prefills")),
    ("Sandbox", ("sandbox_enabled", "bwrap_bin", "sandbox_home", "toolchain_binds",
                 "env_passthrough")),
    ("Agents", ("agents_dir",)),
    ("Transport", ("transport", "http_port")),
]


def _cell(text: object) -> str:
    """Table-safe: escape pipes, collapse whitespace, render empties visibly."""
    s = str(text)
    if s == "":
        return "*(empty)*"
    return s.replace("|", "\\|").replace("\n", " ")


def render() -> str:
    rows = {r["field"]: r for r in config.describe()}
    placed: set[str] = set()
    out: list[str] = [
        START,
        "",
        "<!-- Generated by scripts/gen_config_docs.py from the Config dataclass in",
        "     src/claude_delegate_local/config.py. Do not edit by hand: the docs gate",
        "     regenerates this block and fails the build if it differs. To change a",
        "     default or a description, edit the dataclass field. -->",
        "",
        f"All settings are environment variables. Prefix `{config.env_name('')}`. "
        "List-valued settings are shown comma-separated for readability, but are "
        "**parsed on `os.pathsep`** — `;` on Windows, `:` elsewhere. The rendering is "
        "deliberately platform-independent so this file is byte-identical wherever it "
        "is generated.",
        "",
    ]
    for title, names in SECTIONS:
        present = [n for n in names if n in rows]
        if not present:
            continue
        out += [f"### {title}", "", "| Variable | Default | Description |",
                "| --- | --- | --- |"]
        for name in present:
            r = rows[name]
            placed.add(name)
            default = _cell(r["default"])
            if r["unit"]:
                default = f"{default} {r['unit']}"
            if r["required"]:
                default = "**required**"
            out.append(f"| `{r['env']}` | {default} | {_cell(r['description'])} |")
        out.append("")

    leftover = [n for n in rows if n not in placed]
    if leftover:
        out += ["### Other", "",
                "<!-- These fields matched no section in gen_config_docs.py SECTIONS."
                " Add them to a group. -->", "",
                "| Variable | Default | Description |", "| --- | --- | --- |"]
        for name in leftover:
            r = rows[name]
            out.append(f"| `{r['env']}` | {_cell(r['default'])} | {_cell(r['description'])} |")
        out.append("")

    out += [f"*{len(rows)} settings.*", "", END]
    return "\n".join(out)


def splice(existing: str, block: str) -> str:
    if START in existing and END in existing:
        head = existing.split(START)[0]
        tail = existing.split(END, 1)[1]
        return head + block + tail
    # First run, or someone removed the markers: append rather than clobber prose.
    sep = "" if existing.endswith("\n\n") or not existing else "\n"
    return existing + sep + "\n" + block + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed file is stale")
    args = ap.parse_args()

    block = render()
    existing = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    updated = splice(existing, block)

    if args.check:
        if existing == updated:
            print(f"ok: {TARGET.relative_to(ROOT)} is current "
                  f"({len(config.describe())} settings)")
            return 0
        print(f"STALE: {TARGET.relative_to(ROOT)} does not match the Config dataclass.")
        print("Run: python scripts/gen_config_docs.py\n")
        diff = difflib.unified_diff(
            existing.splitlines(), updated.splitlines(),
            fromfile="committed", tofile="generated", lineterm="", n=1,
        )
        for line in list(diff)[:40]:
            print("  " + line)
        return 1

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(updated, encoding="utf-8")
    verb = "updated" if existing else "created"
    print(f"{verb}: {TARGET.relative_to(ROOT)} ({len(config.describe())} settings)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
