#!/usr/bin/env python
"""Generate the model-facing tool reference from the registry that defines it.

`docs/TOOLS.md` is not written by hand. It is rendered from `tools.REGISTRY` between the
GEN markers, and the docs gate fails if the committed file differs from what this produces.

That matters more here than for any other generated document. A tool description is the
**model-facing contract**: rewording one changes what the delegated model does, so it is a
behaviour change rather than a wording fix (CLAUDE.md). Keeping the reference rendered from
the strings actually sent means the document cannot describe a tool the model was never
given, and a description cannot be improved in prose while the code keeps the old text.

Usage:
    python scripts/gen_tools_docs.py           # write
    python scripts/gen_tools_docs.py --check   # exit 1 if stale, print a diff
"""

from __future__ import annotations

import argparse
import difflib
import sys
import tempfile
from pathlib import Path

# Read the real source, never a cached compile. Python validates a .pyc on (mtime, size),
# so an edit that changes a description WITHOUT changing the file's byte length can be
# missed inside a single filesystem timestamp tick -- and this script would then report the
# document as current against code that no longer exists, which is the exact failure it is
# supposed to catch. `-B` is not sufficient: it stops WRITING a cache, not reading a stale
# one. Redirecting the cache to an empty temp directory forces a fresh compile.
sys.pycache_prefix = tempfile.mkdtemp(prefix="cdl-gentools-pyc-")

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from claude_delegate_local import tools  # noqa: E402

TARGET = ROOT / "docs" / "TOOLS.md"
START = "<!-- GEN:TOOLS:START -->"
END = "<!-- GEN:TOOLS:END -->"


def _cell(text: object) -> str:
    """Table-safe: escape pipes, collapse whitespace, render empties visibly."""
    s = str(text)
    if s == "":
        return "*(empty)*"
    return s.replace("|", "\\|").replace("\n", " ")


def render() -> str:
    out: list[str] = [
        START,
        "",
        "<!-- Generated by scripts/gen_tools_docs.py from the registry in",
        "     src/claude_delegate_local/tools.py. Do not edit by hand: the docs gate",
        "     regenerates this block and fails the build if it differs. A description is",
        "     the model-facing contract, so edit it in the code and regenerate. -->",
        "",
        ("These are the tools the **delegated model** may call inside a delegation. They "
         "are not the MCP tools Claude calls, which are described in "
         "[ARCHITECTURE.md](ARCHITECTURE.md) -- this sentence used to name two of them and "
         "had been wrong since ADR-0042 added a third, so it now points instead."),
        "",
        ("Which of them a given delegation actually gets is its resolved `allowed_tools` "
         "set, enforced both when the list is declared to the model and again when a call "
         "arrives, because a model can call a tool it was never offered."),
        "",
    ]
    for name, tool in tools.REGISTRY.items():
        schema = tool.spec.input_schema
        props: dict[str, object] = schema.get("properties", {})  # type: ignore[assignment]
        required = set(schema.get("required", []))  # type: ignore[arg-type]
        out += [f"## `{name}`", "", tool.spec.description, ""]
        if props:
            out += ["| Argument | Type | Required | Description |",
                    "| --- | --- | --- | --- |"]
            for arg, meta in props.items():
                meta_d: dict[str, object] = meta  # type: ignore[assignment]
                out.append(
                    f"| `{arg}` | {_cell(meta_d.get('type', ''))} | "
                    f"{'yes' if arg in required else 'no'} | "
                    f"{_cell(meta_d.get('description', ''))} |")
            out.append("")
    out += [f"*{len(tools.REGISTRY)} tools.*", "", END]
    return "\n".join(out)


def splice(existing: str, block: str) -> str:
    if START in existing and END in existing:
        head = existing.split(START, maxsplit=1)[0]
        tail = existing.split(END, 1)[1]
        return head + block + tail
    # First run, or someone removed the markers: append rather than clobber prose.
    sep = "" if existing.endswith("\n\n") or not existing else "\n"
    return existing + sep + "\n" + block + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed file is stale")
    args = ap.parse_args()

    block = render()
    existing = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    updated = splice(existing, block)

    if args.check:
        if existing == updated:
            print(f"ok: {TARGET.relative_to(ROOT)} is current "
                  f"({len(tools.REGISTRY)} tools)")
            return 0
        print(f"STALE: {TARGET.relative_to(ROOT)} does not match the tool registry.")
        print("Run: python scripts/gen_tools_docs.py\n")
        diff = difflib.unified_diff(
            existing.splitlines(), updated.splitlines(),
            fromfile="committed", tofile="generated", lineterm="", n=1,
        )
        for line in list(diff)[:40]:
            print("  " + line)
        return 1

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(updated, encoding="utf-8")
    verb = "updated" if existing else "created"
    print(f"{verb}: {TARGET.relative_to(ROOT)} ({len(tools.REGISTRY)} tools)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
